---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt::default]
  - name: centos-7.2
    run_list:
      - recipe[yum-epel::default]
  - name: centos-6.7
    run_list:
      - recipe[yum-epel::default]
  - name: centos-5.11
    run_list:
      - recipe[yum-epel::default]

suites:
  - name: default
    run_list:
      - recipe[collectd::default]
  - name: userchange
    run_list:
      - recipe[collectd::default]
      - recipe[collectd::_test_plugin]
    attributes:
      collectd:
        service_user: 'root'
        service_group: 'root'

