require 'chefspec/berkshelf'
require 'poise_boiler/spec_helper'
require_relative '../../../libraries/collectd_plugin'

describe CollectdCookbook::Resource::CollectdPlugin do
  step_into(:collectd_plugin)
  context 'enables syslog plugin' do
    recipe do
      collectd_plugin 'syslog' do
        options do
          log_level 'info'
        end
      end
    end

    it { is_expected.to render_file('/etc/collectd.d/syslog.conf').with_content(<<-EOH.chomp) }
# This file is autogenerated by Chef.
# Do not edit; All changes will be overwritten!
LoadPlugin "syslog"
<Plugin "syslog">
        LogLevel "info"
</Plugin>
EOH
  end
end
